config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :book_comments
  end

  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    # 一対多の一のほう

    has_many :book_comments, dependent: :destroy
    # Userモデル、Bookモデルのインスタンスは複数のBookCommentモデルのインスタンスと関連付けられる
    # dependent: :destroyオプションによって、UserやBookが削除された場合に関連するBookCommentも同時に削除される

    has_one_attached :image
    # ActiveStorageを紐付け
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :books
    # 一対多の多のほう

    has_many :book_comments, dependent: :destroy
    # Userモデル、Bookモデルのインスタンスは複数のBookCommentモデルのインスタンスと関連付けられる
    # dependent: :destroyオプションによって、UserやBookが削除された場合に関連するBookCommentも同時に削除される

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    # バリデーション

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    before_action :login_required

    protect_from_forgery with: :exception
    # トークン生成

    private
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
        redirect_to login_url unless current_user
    end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        comment = current_user.book_comments.new(book_comment_params)
        comment.book_id = book.id
        comment.save!
        redirect_to request.referer
      end
      # URLのbook_idから関連する本を見つける
      # 次に、現在のユーザーによる新しいコメントを作成
      # comment.book_id = book.idで作成したコメントに関連する本のIDを設定・保存
      # リクエスト元のページにリダイレクト

      # saveとsave!の違い
      # saveは、バリデーションに失敗するとfalseを返す
      # save!は、バリデーションに失敗するとActiveRecord::RecordInvalidという例外を発生させる
      # save!はエラーを厳しくチェックするバージョンのsaveだと言える

      
      def destroy
        comment = BookComment.find(params[:id])
        comment.destroy
        redirect_to request.referer
      end
      # 与えられたコメントのIDを使用し、対応するコメントを見つけて削除
      # リクエスト元のページにリダイレクト
      
      private
      
      def book_comment_params
        params.require(:book_comment).permit(:comment)
      end
      # ストロングパラメータ

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def update
    book = current_user.books.find(params[:id])
    book.update!(book_params)
    redirect_to books_url
  end

  def create
    book = current_user.books.new(book_params)
    book.save!
    redirect_to books_url, notice: "書籍『#{book.name}』を登録しました。"
  end

  def destroy
    book = current_user.books.find(params[:id])
    book.destroy
    redirect_to books_url
  end

  private
    def book_params
      params.require(:book).permit(:isbn, :ndc, :name, :auther, :price, :publisher, :published, :notes, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      # ぼっち演算子「&」オブジェクトの中身がnullのときfalseを返す
      # authenticateメソッド
      session[:user_id] = user.id
      redirect_to books_path
      # このコードにより
      # 誰もログインしていない状態 => session[:user_id]はnull
      # ログインされている状態 => session[:user_id]にログイン中のユーザーIDが入る

    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end
    
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :login_required, only: [:new, :create]
  # ログイン画面で新規登録するための処理
  # 新規登録に関わるアクション(new, create)をリダイレクトから除外

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def create
    user = User.new(user_params)
    user.save!
    redirect_to users_url, notice: "「#{user.name}」を登録しました。"
  end

  def update
    user = User.find(params[:id])
    user.update!(user_params)
    redirect_to users_url
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_url
  end


  private
    def user_params
      # ストロングパラメータ：意図しない（安全では無い）データの登録・更新を防ぐ
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<!-- コメントフォーム(部分テンプレ) -->

<%= form_with model: [book, book_comment] do |f| %>
  <%= f.text_area :comment, size: "60x3", placeholder: "コメントする" %>
  <%= f.submit "送信" %>
<% end %>

<!-- form_withに対して、[book, book_comment]のように、配列で2つの変数を指定
特定の本に対してコメントを投稿する場合、そのコメントはその本と関連付けられる
この場合、コメント投稿フォームはコメントの内容だけでなく、
どの本に対するコメントなのかもフォームで指定する必要がある-->

<!-- rows:'x'：テキストエリアをx行に表示
placeholder: テキストエリア内に表示されるテキストを指定
class: "w-100"：Bootstrapのクラスで、テキストエリアの幅を100%（width: 100%）に設定-->

app/views/books/_comment.html.erb
<!-- パーシャル：コメント一覧表記 -->
<h2>コメント一覧</h2>



<div class="commentarea">
    <table>
        <tbody>
            <% book.book_comments.each do |book_comment| %>
                <tr>
                    <td>
                        <%= link_to user_path(book_comment.user) do %>
                            <%= book_comment.user.name %>
                        <% end %>
                    </td>
                    <td><%= book_comment.comment %></td>
                    <td>
                        <% if book_comment.user == current_user %>
                        <%= link_to "削除", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-sm btn-danger float-end" %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
</div>

app/views/books/_form.html.erb
<!-- パーシャル -->
<!-- 新規登録画面と編集画面に共通のview -->

<%= form_with model: book, local: true do |f| %>

    <div class="field">
        <!-- ISBN -->
        <%= f.label :isbn %><br>
        <%= f.text_field :isbn %><br>
    </div>

    <div class="field">
        <!-- NDC -->
        <!-- クソ長プルダウン取扱注意 -->
        <%= f.label :ndc %><br>
        <%= f.select :ndc, ['000　総記', '010　図書館・図書館学', '020　図書・書誌学', '030　百科事典', '040　一般論文集・一般講演集','050　逐次刊行物', '060　団体', '070　ジャーナリズム・新聞', '080　叢書・全集・選集', '090　貴重書・郷土資料　その他の特別コレクション', '100　哲学', '110　哲学各論', '120　東洋思想', '130　西洋哲学', '140　心理学', '150　倫理学・道徳', '160　宗教', '170　神道', '180　仏教', '190　キリスト教', '200　歴史', '210　日本史', '220　アジア史・東洋史', '230　ヨーロッパ史・西洋史', '240　アフリカ史', '250　北アメリカ史', '260　南アメリカ史', '270　オセアニア史・両極地方史', '280　伝記', '290　地理・地誌・紀行', '300　社会科学', '310　政治', '320　法律', '330　経済', '340　財政', '350　統計', '360　社会', '370　教育', '380　風俗習慣・民俗学・民族学', '390　国防・軍事', '400　自然科学', '410　数学', '420　物理学', '430　化学', '440　天文学・宇宙科学', '450　地球科学・地学', '460　生物科学・一般生物学', '470　植物学', '480　動物学', '490　医学・薬学', '500　技術・工学', '510　建設工学・土木工学', '520　建築学', '530　機械工学・原子力工学', '540　電気工学・電子工学', '550　海洋工学・船舶工学・兵器', '560　金属工学・鉱山工学', '570　化学工業', '580　製造工業', '590　家政学・生活科学', '600　産業', '610　農業', '620　園芸', '630　蚕糸業', '640　畜産業・獣医学', '650　林業', '660　水産業', '670　商業', '680　運輸・交通', '690　通信事業', '700　芸術・美術', '710　彫刻', '720　絵画・書道', '730　版 画', '740　写真・印刷', '750　工芸', '760　音楽・舞踊', '770　演劇・映画', '780　スポーツ・体育', '790　諸芸・娯楽', '800　言語', '810　日本語', '820　中国語　その他の東洋の諸言語', '830　英語', '840　ドイツ語', '850　フランス語', '860　スペイン語', '870　イタリア語', '880　ロシア語', '890　その他の諸言語', '900　文学', '910　日本文学', '920　中国文学　その他の東洋文学', '930　英米文学', '940　ドイツ文学', '950　フランス文学', '960　スペイン文学', '970　イタリア文学', '980　ロシア・ソヴィエト文学', '990　その他の諸文学']%><br>
    </div>

    <div class="field">
        <!-- 書籍名 -->
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>
    </div>

    <div class="field">
        <!-- 著者名 -->
        <%= f.label :auther %><br>
        <%= f.text_field :auther %><br>
    </div>

    <div class="field">
        <!-- 価格 -->
        <%= f.label :price %><br>
        <%= f.number_field :price %><br>
    </div>

    <div class="field">
        <!-- 出版社 -->
        <%= f.label :publisher %><br>
        <%= f.text_field :publisher %><br>
    </div>

    <div class="field">
        <!-- 出版日 -->
        <%= f.label :published %><br>
        <%= f.date_field :published %><br>
    </div>

    <div class="field">
        <!-- 備考 -->
        <%= f.label :notes %><br>
        <%= f.text_area :notes, size: "40x10" %><br>
    </div>

    <div class="field">
        <!-- 画像 -->
        <%= f.label :image %><br>
        <%= f.file_field :image %><br>
    </div>

    <div class="actions">
        <%= f.submit('登録') %>
    </div>

<% end %>

app/views/books/edit.html.erb
<h1>書籍情報の編集</h1>

<%= link_to '一覧へ戻る', books_path %>

<%= render partial: 'form', locals: { book: @book } %>

app/views/books/index.html.erb
<h1>書籍一覧</h1>
<p>登録された書籍一覧を表示しています。書籍名から詳細が確認できます。</p>

<%= link_to '>>> 書籍新規登録', new_book_path %>

<table>

    <thead>
        <tr>
        <th><%= Book.human_attribute_name(:ndc) %></th>
        <th><%= Book.human_attribute_name(:name) %></th>
        <th><%= Book.human_attribute_name(:auther) %></th>
        <th><%= Book.human_attribute_name(:publisher) %></th>
        <th><%= Book.human_attribute_name(:published) %></th>
        <th><%= Book.human_attribute_name(:reviewrd_user) %></th>
        <th><%= Book.human_attribute_name(:notes) %></th>
        <th><%= Book.human_attribute_name(:book_comments) %></th>
        </tr>
    </thead>

    <tbody>
        <% @books.each do|book| %>

            <tr style="background-color:<%= cycle('#FFFFFF', '#ffffe0') %>">
                <td><%= book.ndc %></td>
                <td><%= link_to book.name, book %></td>
                <td><%= book.auther %></td>
                <td><%= book.publisher %></td>
                <td><%= book.published %></td>
                <td><%= book.user.name %></td>
                <td><%= truncate(book.notes, length: 30) %></td>
                <td><%= book.book_comments.count %></td>

                <% if book.user == @current_user %>
                    <td><%= link_to '編集', edit_book_path(book) %></td>
                    <td><%= link_to '削除', book, method: :delete, data: {confirm: "削除しますか？"}  %></td>
                <% else %>
                    <td></td>
                    <td></td>
                <% end %>

            </tr>
        <% end %>
        
    </tbody>

</table>

app/views/books/new.html.erb
<h1>書籍新規登録</h1>

<%= link_to '一覧へ戻る', books_path %>

<%= render partial: 'form', locals: { book: @book } %>

app/views/books/show.html.erb
<h1>書籍詳細</h1>

<%= link_to '書籍一覧にもどる', books_path %>

<table style="width: 800px;">
<!-- テーブル幅指定 見づらいんだもん… -->
    <tbody>

        <tr>
            <th><%= Book.human_attribute_name(:id) %></th>
            <td><%= @book.id %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:isbn) %></th>
            <td><%= @book.isbn %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:ndc) %></th>
            <td><%= @book.ndc %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:name) %></th>
            <td><%= @book.name %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:auther) %></th>
            <td><%= @book.auther %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:price) %></th>
            <td><%= @book.price %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:publisher) %></th>
            <td><%= @book.publisher %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:published) %></th>
            <td><%= @book.published %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:reviewrd_user) %></th>
            <td><%= @book.user.name %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:created_at) %></th>
            <td><%= @book.created_at %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:updated_at) %></th>
            <td><%= @book.updated_at %></td>
        </tr>

        <tr>
            <th><%= Book.human_attribute_name(:notes) %></th>
            <td><%= @book.notes %></td>
        </tr>

    </tbody>
</table>



<%= render partial: 'comment', locals: { book: @book } %>
<!-- パーシャル：コメント一覧 -->

<% if @book.user == @current_user %>
    <%= link_to '編集', edit_book_path %>
    <!-- 編集ボタン -->
    <%= link_to '削除', @book, method: :delete, data: {confirm: "削除しますか？"} %>
    <!-- 削除ボタン -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>

  </head>

  <body>
    <div class="base">

      <ul class="menu"><!-- メニュー -->
        <% if current_user %>
          <li><%= link_to '書籍一覧', books_path %></li>
          <li><%= link_to 'ユーザー一覧', users_path %></li>
          <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>

      <div class="text">
        <% if current_user %>
          <%= "現在『#{current_user.name}』でログインしています" %>
        <% else %>
          <%= "ログインしてください" %>
        <% end %> 
        
        <%= yield %>
      </div>

    </div> 
  </body>
</html>

app/views/users/_form.html.erb
<!-- パーシャル -->
<!-- 新規登録画面と編集画面に共通のview -->

<%= form_with model: user, local: true do |f| %>

    <div class="field">
        <!-- ユーザー名 -->
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>
    </div>

    <div class="field">
        <!-- e-mail -->
        <%= f.label :email %><br>
        <%= f.text_field :email %><br>
    </div>

    <div class="field">
        <!-- 生パスワード -->
        <%= f.label :password %><br>
        <%= f.text_field :password %><br>
    </div>

    <div class="field">
        <!-- 確認用パスワード -->
        <%= f.label :password_confirmation %><br>
        <%= f.text_field :password_confirmation %><br>
    </div>

    <div class="actions">
        <%= f.submit('登録') %>
    </div>

<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報変更</h1>

<%= link_to 'ユーザー一覧', users_path %>

<%= render partial: 'form', locals: { user: @user } %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= link_to '>>> 新規ユーザー登録', new_user_path %>

<table>

    <thead>
        <tr>
        <th><%= User.human_attribute_name(:name) %></th>
        <th><%= User.human_attribute_name(:email) %></th>
        <th><%= User.human_attribute_name(:password_digest) %></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do|user| %>

            <tr>
                <td><%= link_to user.name, user %></td>
                <!-- 「書籍名に詳細表示へのリンクをつける」 -->
                <td><%= user.email %></td>
                <td><%= user.password_digest %></td>

            <% if user == @current_user %>
                <td><%= link_to '編集', edit_user_path(user) %></td>
                <!-- 編集ボタン -->
                <td><%= link_to '削除', user, method: :delete, data: {confirm: "削除しますか？"} %></td>
                <!-- 削除ボタン -->
            <% end %>

            </tr>
        <% end %>
        
    </tbody>

</table>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>

<%= link_to '一覧', users_path %>

<%= render partial: 'form', locals: { user: @user } %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<%= link_to 'ユーザー一覧', users_path %>

    <table>
        <tbody>

            <tr>
                <th><%= User.human_attribute_name(:id) %></th>
                <!-- カラム名表示：カラム名を表示するときは、モデル.human.attribute_name(カラム名のシンボル)で記述する -->
                <td><%= @user.id %></td>
                <!-- データ名表示：指定されたデータのidカラムに入っているデータを表示 -->
            </tr>

            <tr>
                <th><%= User.human_attribute_name(:name) %></th>
                <td><%= @user.name %></td>
            </tr>

            <tr>
                <th><%= User.human_attribute_name(:email) %></th>
                <td><%= @user.email %></td>
            </tr>

            <tr>
                <th><%= User.human_attribute_name(:password_digest) %></th>
                <td><%= @user.password_digest %></td>
            </tr>

            <tr>
                <th><%= User.human_attribute_name(:created_at) %></th>
                <td><%= @user.created_at %></td>
            </tr>

            <tr>
                <th><%= User.human_attribute_name(:updated_at) %></th>
                <td><%= @user.updated_at %></td>
            </tr>

        </tbody>
    </table>
<% if @user == @current_user %>
    <%= link_to '編集', edit_user_path %>
<!-- 編集ボタン -->
    <%= link_to '削除', @user, method: :delete, data: {confirm: "削除しますか？"} %>
<!-- 削除ボタン -->
<% end %>